version: '3'
services:
  frontend:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
    - ./:/usr/src/app
    command: sh -c "cd app && npm start"
    ports:
    - "3000:3000"
