version: '3.7'

services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "4306:3306"
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pssword
    security_opt:
      - seccomp:unconfined
  redis:
    image: "redis:5.0.5"
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - "./data/redis:/data"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/myapp
    command: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      TZ: Asia/Tokyo
      REDIS_URL: redis://redis:6379/0
volumes:
  db:
    driver: local
  bundle:
    driver: local
